// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   
     public static final class DriveConstants {
        public static final double maxSpeed = 0.5;
        public static final int leftFrontId = 1;
          public static final int leftBackId = 2;
          public static final int rightFrontId = 3;
          public static final int rightBackId = 4;

          //wheelDiameter je v metrech
          public static final double wheelDiameter = 0.1524;
          public static final double gearRatio = 0.2;

          public static final double driveForwardProportion = 0.025;
       
     }
    
     public static final class ArmConstants{
          public static final int intakeLiftId = 7;
          public static final int intakeSpinId = 10;
          public static final double intakeSpinSpeedIn = 0.2;
          public static final double intakeSpinSpeedOut = -0.7;

          public static final double intakeSpeedUp = 0.25;
          public static final double intakeSpeedDown = -0.25;
          public static final double intakeMaxPosition = 0;
         public static final double intakeMinPosition = -74;

          public static final int shooterLowerId = 8;
          public static final int shooterHigherId = 9;
          public static final double shooterSpeedFastHigher = 0.8;
          public static final double shooterSpeedFastLower = 0.85;
          public static final double shooterSpeedSlowHigher = 0.17;
          public static final double shooterSpeedSlowLower = 0.20;
          public static final double shooterSpeedIn = -0.2;

          public static final int climberLeftId = 5;
          public static final int climberRightId = 6;

          public static final double climberSpeedUp = 0.15;
          public static final double climberSpeedDown= -0.15;
          
          public static final double climberSpeedHYPERDOWN = -1;
          public static final double climberSpeedHYPERUP = 1;

          public static final double climberMaxPosition = 0;
          public static final double climberMinPosition = -0;


     }
    
}

