// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

package frc.robot;

import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import frc.robot.commands.AutonCommands.*;
import frc.robot.subsystems.*;

/**
 * This class is where the bulk of the robot should be declared.  Since Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in the {@link Robot}
 * periodic methods (other than the scheduler calls).  Instead, the structure of the robot
 * (including subsystems, commands, and button mappings) should be declared here.
 */
public class RobotContainer {

    private static final RobotContainer robotContainer = new RobotContainer();

    public final DriveTrain driveTrain = new DriveTrain();
    public final Intake intake = new Intake();
    public final Shooter shooter = new Shooter();
    public final Climber climber = new Climber();
    public final Gyro gyro = new Gyro();
    // Joysticks
    private final CommandXboxController driveController = new CommandXboxController(0);
    private final CommandXboxController armController = new CommandXboxController(1);
    // A chooser for autonomous commands
    private final SendableChooser<Command> chooser = new SendableChooser<>();

    /**
     * The container for the robot.  Contains subsystems, OI devices, and commands.
     */
    private RobotContainer() {
        // SmartDashboard Buttons
        chooser.addOption("Auto_0_just_shoot", new AutonJustShoot());
        chooser.addOption("Auto_1_from_source_side blue", new AutonFromSourceBlue());
        chooser.addOption("Auto_1_from_source_side red", new AutonFromSourceRed());
        chooser.addOption("Auto_2_from_middle", new AutonFromMiddle());
        chooser.addOption("Auto_3_shoot_go_forward", new AutonShootGoForward());
        chooser.addOption("Auto_4_shoot_turn_right_go_forward", new AutonShootTurnRightGoForward());
        chooser.addOption("Auto_4_shoot_turn_left_go_forward", new AutonShootTurnLeftGoForward());

        // Configure the button bindings
        configureButtonBindings();

        // Configure autonomous sendable chooser
        chooser.setDefaultOption("Auto_0_just_shoot", new AutonJustShoot());

        SmartDashboard.putData("Auto Mode", chooser);
    }

    public static RobotContainer getInstance() {
        return robotContainer;
    }

    public CommandXboxController getDriveController() {
        return driveController;
    }

    public CommandXboxController getArmController() {
        return armController;
    }

    /**
     * Use this method to define your button->command mappings.  Buttons can be created by
     * instantiating a {@link GenericHID} or one of its subclasses ({@link
     * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing it to a
     * {@link edu.wpi.first.wpilibj2.command.button.JoystickButton}.
     */
    private void configureButtonBindings() {
    }

    public CommandXboxController getControllerXboxController(int id) {
        if (id == 1) {
            return driveController;
        }
        if (id == 2) {
            return armController;
        }
        return null;
    }

    public void updateSmartDashboard() {
        SmartDashboard.putNumber("Arm position", intake.getPosition());
        SmartDashboard.putNumber("Left-climber position", (climber.getPositionLeft() / Constants.ArmConstants.climberMinPosition) * 100);
        SmartDashboard.putNumber("Right-climber position", (climber.getPositionRight() / Constants.ArmConstants.climberMinPosition) * 100);
        SmartDashboard.putNumber("Gyro Normalized angle", gyro.getNormalizedNavxAngle());
        SmartDashboard.putString("Intake-Lift brake mode", intake.getMotorMode());
        SmartDashboard.putNumber("Drive Encoder Position", driveTrain.getDistanceForward());
        SmartDashboard.putBoolean("Is Fast", driveTrain.isFast);
        SmartDashboard.putNumber("Left front motor temperature", driveTrain.leftFront.getMotorTemperature());
        SmartDashboard.putNumber("Left Back motor temperature", driveTrain.leftBack.getMotorTemperature());
        SmartDashboard.putNumber("Right front motor temperature", driveTrain.rightFront.getMotorTemperature());
        SmartDashboard.putNumber("Right Back motor temperature", driveTrain.rightBack.getMotorTemperature());
        SmartDashboard.putBoolean("is intaked", intake.isIntaked);

    }

    /**
     * Use this to pass the autonomous command to the main {@link Robot} class.
     *
     * @return the command to run in autonomous
     */
    public Command getAutonomousCommand() {
        // The selected command will be run in autonomous
        return chooser.getSelected();
    }

}

